services:
  db:
    image: mysql:8.0
    container_name: mysql-amigo-secreto
    environment:
      MYSQL_DATABASE: db_amigo_secreto
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: api-secret-friend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # ConexÃ£o Banco
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db_amigo_secreto?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_password

      # E-mail
      SPRING_MAIL_USERNAME: ${EMAIL_USER}
      SPRING_MAIL_PASSWORD: ${EMAIL_PASS}

      # IA Groq
      GROQ_API_KEY: ${GROQ_KEY}

      # OAuth2 Google (ADICIONADO AQUI) ðŸ‘‡
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

volumes:
  mysql_data: