services:
  db:
    image: postgres:15-alpine
    container_name: postgres-amigo-secreto
    environment:
      POSTGRES_DB: amigo_secreto_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${password_data}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: api-secret-friend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Conex√£o Banco
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/amigo_secreto_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${password_data}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      # E-mail
      SPRING_MAIL_USERNAME: ${EMAIL_USER}
      SPRING_MAIL_PASSWORD: ${EMAIL_PASS}

      # IA Groq
      GROQ_API_KEY: ${GROQ_KEY}

      # OAuth2 Google
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

volumes:
  postgres_data: